"""Render ``leaderboard/data.json`` to a static HTML site.

Output is a single self-contained ``index.html`` — no external CSS,
no JavaScript. The leaderboard is meant to be cacheable, embeddable,
and trivially trustworthy.
"""

from __future__ import annotations

from html import escape
from pathlib import Path

from benchprobe.core.leaderboard import LeaderboardStore
from benchprobe.core.verdict import VerdictKind

_INDEX_CSS = """
body { font-family: -apple-system, system-ui, sans-serif; max-width: 1100px; margin: 2em auto; padding: 0 1em; color: #1d1f21; }
h1 { border-bottom: 1px solid #d0d0d0; padding-bottom: .25em; }
table { border-collapse: collapse; width: 100%; }
th, td { border: 1px solid #d0d0d0; padding: .35em .55em; text-align: left; font-size: 90%; }
th { background: #f6f8fa; }
.pass { color: #117a3a; font-weight: 600; }
.vuln { color: #b3261e; font-weight: 600; }
.inc  { color: #8a6d00; font-weight: 600; }
.cell-pass { background: #e6f4ea; }
.cell-vuln { background: #fde8e6; }
.cell-inc  { background: #fdf3d6; }
small.sha { font-family: ui-monospace, monospace; color: #555; }
footer { margin-top: 3em; color: #666; font-size: 85%; }
"""


def render_site(store: LeaderboardStore, out_dir: Path) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    families: list[str] = []
    for entry in store.entries:
        for fam in entry.family_verdicts:
            if fam not in families:
                families.append(fam)
    families.sort()

    rows: list[str] = []
    for entry in sorted(store.entries, key=lambda e: e.benchmark):
        overall_class = "pass" if entry.passing else "vuln"
        overall_text = "PASS" if entry.passing else "FAIL"
        cells: list[str] = []
        for fam in families:
            verdict = entry.family_verdicts.get(fam)
            if verdict is None:
                cells.append("<td>—</td>")
            elif verdict is VerdictKind.PASS:
                cells.append("<td class='cell-pass'>✓</td>")
            elif verdict is VerdictKind.VULNERABLE:
                cells.append("<td class='cell-vuln'>✗</td>")
            else:
                cells.append("<td class='cell-inc'>?</td>")
        evidence_link = ""
        if entry.evidence_url:
            evidence_link = (
                f"<a href='{escape(entry.evidence_url)}'>evidence</a>"
            )
        rows.append(
            "<tr>"
            f"<td><b>{escape(entry.benchmark)}</b><br>"
            f"<small class='sha'>{escape(entry.version_sha[:12])}</small></td>"
            f"<td class='{overall_class}'>{overall_text}</td>"
            + "".join(cells)
            + f"<td>{evidence_link}</td>"
            + f"<td>{escape(entry.audited_at.strftime('%Y-%m-%d'))}</td>"
            "</tr>"
        )

    family_headers = "".join(
        f"<th><code>{escape(f)}</code></th>" for f in families
    )

    html = (
        "<!doctype html>\n<html lang='en'>\n<head>\n"
        "<meta charset='utf-8'><title>benchprobe leaderboard</title>\n"
        f"<style>{_INDEX_CSS}</style>\n"
        "</head>\n<body>\n"
        "<h1>benchprobe leaderboard</h1>\n"
        "<p>Each row is one benchmark audited against the Berkeley/RDI exploit families. "
        "✓ = no exploit reachable; ✗ = exploit reachable per published evidence; "
        "? = adapter could not collect the artifact required to decide.</p>\n"
        "<table><thead><tr>"
        "<th>Benchmark</th><th>Overall</th>"
        + family_headers
        + "<th>Evidence</th><th>Audited</th>"
        + "</tr></thead><tbody>"
        + "".join(rows)
        + "</tbody></table>\n"
        "<footer>Generated by benchprobe. Schema version "
        f"{store.schema_version}. Methodology: see "
        "<a href='https://rdi.berkeley.edu/blog/trustworthy-benchmarks/'>"
        "Berkeley RDI</a> and the project README.</footer>\n"
        "</body></html>\n"
    )
    (out_dir / "index.html").write_text(html, encoding="utf-8")
